entrypoint: gunicorn -b :$PORT main:app
env: flex

runtime: python
runtime_config: 
  python_version: "3.11"
  operating_system: "ubuntu22"

manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 4
  # disk_size_gb: 20

handlers:
- url: /.*
  script: auto
